"""Backward-compatible public API re-exports for Copy-Space Guard."""
from .anonymize import anonymize_demands_csv, anonymize_schedule_csv
from .bounds import (
    BOUNDS_REASON_AUTO_EXHAUSTIVE,
    BOUNDS_REASON_AUTO_PARTIAL,
    BOUNDS_REASON_FRACTIONAL_HEURISTIC_PARTIAL,
    BOUNDS_REASON_FRACTIONAL_ODD_SUBSET,
    BOUNDS_REASON_READ1_WRITE1_COMPLETE,
    MAX_EXHAUSTIVE_SUBSET_LIMIT,
    lower_bound_components,
    lower_bound_ticks,
)
from .bounds_reason import BoundsReason
from .io import (
    demand_map,
    dump_json,
    instance_from_csv,
    iter_schedule_csv_ticks,
    load_config,
    load_json,
    read_demands_csv,
    read_demands_csv_ex,
    schedule_from_csv,
    validate_instance,
    write_schedule_csv,
)
from .roi import compare_reports, compute_roi, roi_cost_per_tick
from .schema import validate_artifact_contract, validate_instance_contract, validate_report_contract, validate_schedule_contract, validate_summary_contract
from .solvers import DEFAULT_EXACT_CHUNK_LIMIT, exact_optimal_ticks, iter_baseline, iter_greedy, solve_baseline, solve_greedy
from .types import Chunk, Demand, Instance, MODEL, MODELS, READ1_WRITE1, STRICT1, Report, Schedule
from .validate import fail_report, gate_report, validate_schedule, validate_schedule_csv, validate_ticks_iter

__all__ = [
    "MODEL",
    "STRICT1",
    "READ1_WRITE1",
    "MODELS",
    "Demand",
    "Chunk",
    "Schedule",
    "Instance",
    "Report",
    "load_json",
    "dump_json",
    "read_demands_csv",
    "read_demands_csv_ex",
    "instance_from_csv",
    "demand_map",
    "validate_instance",
    "iter_schedule_csv_ticks",
    "schedule_from_csv",
    "write_schedule_csv",
    "load_config",
    "lower_bound_components",
    "lower_bound_ticks",
    "MAX_EXHAUSTIVE_SUBSET_LIMIT",
    "BOUNDS_REASON_AUTO_EXHAUSTIVE",
    "BOUNDS_REASON_AUTO_PARTIAL",
    "BOUNDS_REASON_FRACTIONAL_HEURISTIC_PARTIAL",
    "BOUNDS_REASON_FRACTIONAL_ODD_SUBSET",
    "BOUNDS_REASON_READ1_WRITE1_COMPLETE",
    "BoundsReason",
    "iter_baseline",
    "iter_greedy",
    "DEFAULT_EXACT_CHUNK_LIMIT",
    "exact_optimal_ticks",
    "solve_baseline",
    "solve_greedy",
    "fail_report",
    "validate_schedule",
    "validate_schedule_csv",
    "validate_ticks_iter",
    "gate_report",
    "compare_reports",
    "compute_roi",
    "roi_cost_per_tick",
    "validate_artifact_contract",
    "validate_instance_contract",
    "validate_schedule_contract",
    "validate_report_contract",
    "validate_summary_contract",
    "anonymize_demands_csv",
    "anonymize_schedule_csv",
]
